version: "3.8"

services:
  dev_environment_ms_property:
    image: node:20
    container_name: dev_environment_ms_property
    volumes:
      - .:/workspaces/project
    working_dir: /workspaces/project
    command: tail -f /dev/null

  ms_property_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms_property_service
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: tail -f /dev/null
    depends_on:
      - dev_environment_ms_property

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222" 
      - "8222:8222"
